### ISSUE TITLE
Generate intros for entire library?

### ISSUE THREAD

**Issue by qazero** [danrahn/IntroEditorForPlex#1]
Pretty cool project, thank you for your work and efforts on this!

Is it possible to use this to generate intros for an entire library? Right now plex does not reliably generate intros when analyzing an entire library even during maintenance window hours. Sometimes it starts but almost always it get interrupted part way through for some reason or stops for some reason. Other times it never even starts.

It would be nice to be able to use a 3rd party tool like this to initiate calls to plex to detect intros for the entire library and also see the progress of completion in real time from the webui for the entire library. Is something like this possible using this tool?

**Comment by danrahn** [comment]
That's not currently possible with this tool, and I don't think that's something that will be added. One goal I had was to allow this tool to run without PMS itself running to avoid any potential conflicts with multiple sources writing to the database at the same time. Running intro analysis requires the server to be running, so it breaks that contract.

The [Plex Media Scanner command line tool](https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/) has an `--index` option that will generate video preview thumbnails, though it's marked as deprecated, so I'm not sure how reliably it works. From the logs, it looks like it just makes a `PUT` request to `http://127.0.0.1:32400/library/metadata/{metadataId}/index?force=0` for each episode (`metadataId`) in the library.

I may consider writing something that does this, but it would be outside of this specific project, so I'm closing the issue. That said, it does seem like it might fit into [Plex-scripts](https://github.com/Casvt/Plex-scripts), so you could make a request there.

**Comment by danrahn** [comment]
[Changing from completed to not planned]

**Comment by qazero** [comment]
I think you may have misunderstood, I am not trying to generate video index thumbnails. The --index option which you mentioned according to the plex URL you linked will do the following: "Generate a media index file. (Video Preview Thumbnails)". This is not what I was requesting. My request was related to generating intro markers for tv series.

**Comment by danrahn** [comment]
Sorry, you're right, I answered too quickly. Unfortunately I think the only way to force generate intro markers is to analyze each season individually, which could potentially be done in bulk by switching to Season view in a library and using [multi-select](https://support.plex.tv/articles/200392126-using-the-library-view/#multi-select) to select all seasons, then [analyze them](https://i.imgur.com/nTZuDUA.png). You might also be able to use the [Python wrapper around the web api](https://python-plexapi.readthedocs.io/en/latest/introduction.html) to [analyze](https://python-plexapi.readthedocs.io/en/latest/modules/base.html?highlight=analyze#plexapi.base.PlexPartialObject.analyze) all of the [seasons](https://python-plexapi.readthedocs.io/en/latest/modules/video.html?highlight=season#plexapi.video.Season) of a library.
