### ISSUE TITLE
Make Marker Based Off MKV Chapter

### ISSUE THREAD

**Issue by adamjsturge** [danrahn/IntroEditorForPlex#12]
A lot of mkvs come with chapters already marked with "opening" or "recap". I started making a script to export a JSON from the MKV but was researching how to modify markers when I found your repo. Was wondering if your opening to working on this together. In node you need to run `exec("mkvinfo")` and in python there is library called pymkv. I was wondering if this would be a good thing to implement as a part of this or if you could have another way to import a JSON generated by a script. It was a little unclear if the import is meant to override everything or just that series. 

Would love your thoughts as this tool is really cool and I'd love to use it with my script.

**Comment by danrahn** [comment]
I definitely like the idea, but as you may be able to tell from my super delayed response, I haven't had much free time to work on side projects lately, so I can't give any guarantees on if/when I can look at, or even start working on this. To start with though, the JSON import would probably be the easiest to tackle (my existing import feature only work with files exported from this app), but there'd have to be a format specification that works well for general use cases. What is the format of your JSON file from your script?

**Comment by danrahn** [comment]
I've started implementing this with e080a1c3797cfacb56253f6c71d82d610b667d42, which adds a new Chapter option when adding/editing a marker at the episode/movie level. It doesn't use mkvinfo/ffmpeg, but the chapter data parsed by Plex itself during analysis. There are no bulk add/import options yet, but I'm hoping to work on that ~soon.


![image](https://github.com/danrahn/IntroEditorForPlex/assets/7410989/8907c611-bb0b-4d2e-8aae-2ba0c6e1135f)

**Comment by danrahn** [comment]
Bulk adding markers based on chapter data has been implemented with 9ffe1907086542445537c46917eed57a2a3bd976. There's now a 'Chapter Mode' button in the bulk add overlay, which allows you to pick chapters from a baseline" episode and attempt to match those against the chapters in the rest of episodes:

![image](https://github.com/danrahn/IntroEditorForPlex/assets/7410989/af01d584-bedb-432a-a46a-a7361a0d2846)

Hoping to get this into a beta/official release sometime tomorrow. Definitely let me know if you try it out and it doesn't do what you expect.
