### ISSUE TITLE
Ability to export / import intro markers from file

### ISSUE THREAD

**Issue by Raiiyzen** [danrahn/IntroEditorForPlex#2]
Hi,

It would be nice to have the possibility to export and import intro markers from / to a file. Is this possible ?

**Comment by danrahn** [comment]
It's definitely something I can look into. Depending on the exact functionality you're looking for, [`plex_exporter_importer.py`](https://github.com/Casvt/Plex-scripts/blob/main/multiple_servers/plex_exporter_importer.py) might do what you need.

**Comment by Raiiyzen** [comment]
I noticed that during a plex migration, even with exactly the same library paths, I lost all the introduction markers, and from what I have read, if a new episode is added to a current season, all the modified intro markers will be wiped. So we can imagine an import/export system so we don't have to redo all the episodes of the same season. What do you think ?

**Comment by danrahn** [comment]
That's what I was imagining as well. It's something I'll look into adding when I have the time, but no guaranteed timeline. The script I linked above should do exactly what you're looking for though if you want to try that out in the meantime.

**Comment by danrahn** [comment]
The [latest beta](https://github.com/danrahn/IntroEditorForPlex/releases/tag/v2.2.0-beta) attempts to address this, giving you the option to export all markers for a given library, or the entire server. The file can then be used later to bulk-import everything in one go. Narrower scopes at the show/season level should be covered by the existing [purged marker system](https://github.com/danrahn/IntroEditorForPlex/wiki/Usage#purged-markers).

**Comment by danrahn** [comment]
@jaketame - I don't think that's likely, at least in the near term. The best you'll probably get right now is exporting your library using Tautulli's [export feature](https://github.com/Tautulli/Tautulli/wiki/Exporter-Guide) (metadata level 2 should include markers), and then use that to create an NFO.

**Comment by danrahn** [comment]
Closing as this is now in the non-beta release [v2.2.0](https://github.com/danrahn/IntroEditorForPlex/releases/tag/v2.2.0).
